pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                // Убираем cd laravel-app, так как содержимое папки уже в /var/www/html
                sh '''
                    docker exec php_fpm_petProject bash -c "
                        composer install --no-interaction --prefer-dist
                    "
                '''
            }
        }

        stage('Lint & Static Analysis') {
            parallel {
                stage('Check Style') {
                    steps {
                        sh '''
                            docker exec php_fpm_petProject bash -c "
                                vendor/bin/pint --test &&
                                vendor/bin/phpcs
                            "
                        '''
                    }
                }
                stage('PHPStan') {
                    steps {
                        sh '''
                            docker exec php_fpm_petProject bash -c "
                                vendor/bin/phpstan analyse --memory-limit=1G
                            "
                        '''
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    docker exec php_fpm_petProject bash -c "
                        mkdir -p tests/_reports &&
                        vendor/bin/phpunit --log-junit tests/_reports/junit.xml
                    "
                '''
            }
        }
    }

    post {
        always {
            // Здесь путь остается laravel-app/..., так как Jenkins видит файлы 
            // напрямую из репозитория, а не через volume контейнера PHP
            junit 'laravel-app/tests/_reports/*.xml'
        }
    }
}