pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                // Заходим в папку laravel-app перед запуском команд
                sh '''
                    docker exec php_fpm_petProject bash -c "
                        cd /var/www/html/laravel-app &&
                        composer install --no-interaction --prefer-dist
                    "
                '''
            }
        }

        stage('Lint & Static Analysis') {
            parallel {
                stage('Check Style') {
                    steps {
                        sh '''
                            docker exec php_fpm_petProject bash -c "
                                cd /var/www/html/laravel-app &&
                                vendor/bin/pint --test &&
                                vendor/bin/phpcs
                            "
                        '''
                    }
                }
                stage('PHPStan') {
                    steps {
                        sh '''
                            docker exec php_fpm_petProject bash -c "
                                cd /var/www/html/laravel-app &&
                                vendor/bin/phpstan analyse --memory-limit=1G
                            "
                        '''
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    docker exec php_fpm_petProject bash -c "
                        cd /var/www/html/laravel-app &&
                        mkdir -p tests/_reports &&
                        vendor/bin/phpunit --log-junit tests/_reports/junit.xml
                    "
                '''
            }
        }
    }

    post {
        always {
            // Jenkins ищет файлы в своем workspace, поэтому путь без docker exec
            junit 'laravel-app/tests/_reports/*.xml'
        }
    }
}
